export const MENU = [
    {
        code: 'HOME',
        icon: 'home',
        label: 'Home',
        isDisplay: true,
        route: { path: '/home' },
    },
    {
        menu: 'Input',
        menuIcon: 'app_registration',
        menuLabel: 'Input',
        path: './input',
        isDisplay: true,
        data: { moduleName: 'Input' },
        label: 'Input',
        icon: 'app_registration',
        code: 'Input',
        route: { path: '/input' },
    },
    {
        menu: 'Card',
        menuIcon: 'app_registration',
        menuLabel: 'Card',
        path: './card',
        isDisplay: true,
        data: { moduleName: 'Card' },
        label: 'Card',
        icon: 'app_registration',
        code: 'Card',
        route: { path: '/card' },
    },
    {
        menu: 'Table',
        menuIcon: 'app_registration',
        menuLabel: 'Table',
        path: './table',
        isDisplay: true,
        data: { moduleName: 'Table' },
        label: 'Table',
        icon: 'app_registration',
        code: 'Table',
        route: { path: '/table' },
    },
    {
        menu: 'Button',
        menuIcon: 'app_registration',
        menuLabel: 'Button',
        path: './button',
        isDisplay: true,
        data: { moduleName: 'Button' },
        label: 'Button',
        icon: 'app_registration',
        code: 'Button',
        route: { path: '/button' },
    },
    {
        menu: 'Expansion',
        menuIcon: 'app_registration',
        menuLabel: 'Expansion',
        path: './expansion',
        isDisplay: true,
        data: { moduleName: 'Expansion' },
        label: 'Expansion',
        icon: 'app_registration',
        code: 'Expansion',
        route: { path: '/expansion' },
    },
    {
        menu: 'Criteria',
        menuIcon: 'app_registration',
        menuLabel: 'Criteria',
        path: './criteria',
        isDisplay: true,
        data: { moduleName: 'Criteria' },
        label: 'Criteria',
        icon: 'app_registration',
        code: 'Criteria',
        route: { path: '/criteria' },
    },
    {
        menu: 'Calendar',
        menuIcon: 'calendar_month',
        menuLabel: 'Calendar',
        path: './calendar',
        isDisplay: true,
        data: { moduleName: 'Calendar' },
        label: 'Calendar',
        icon: 'calendar_month',
        code: 'Calendar',
        route: { path: '/calendar' },
    }
];
