import { Component, signal } from '@angular/core';
import {
  DxLookupModalConfig,
  KeyValueModel,
} from 'projects/ng-dijta/src/public-api';

@Component({
  selector: 'app-criteria',
  templateUrl: './criteria.html',
})
export class Criteria {
  readonly panelOpenState = signal(false);
  lookup: any;
  operatorsBasedOnFields = {
    Text: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    Number: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    Date: [
      { keyTt: 'AgeinDays', valueTt: 'Age in Day' },
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '${THISFQ}', valueTt: 'Current FQ' },
      { keyTt: '${THISFY}', valueTt: 'Current FY' },
      { keyTt: '${THISMONTH}', valueTt: 'Current Month' },
      { keyTt: '${THISWEEK}', valueTt: 'Current Week' },
      { keyTt: 'DueinDays', valueTt: 'Due in Days' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: '>', valueTt: 'greater_than' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '${LASTMONTH}', valueTt: 'Last Month' },
      { keyTt: '${LASTWEEK}', valueTt: 'Last Week' },
      { keyTt: '${LASTYEAR}', valueTt: 'Last Year' },
      { keyTt: '<', valueTt: 'less_than' },
      { keyTt: '${NEXTFQ}', valueTt: 'Next FQ' },
      { keyTt: '${NEXTFY}', valueTt: 'Next FY' },
      { keyTt: '${NEXTMONTH}', valueTt: 'Next Month' },
      { keyTt: 'NEXTWEEK', valueTt: 'Next Week' },
      { keyTt: '${NEXTYEAR}', valueTt: 'Next Year' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'not_between', valueTt: 'not_between' },
      { keyTt: '${PREVFQ}', valueTt: 'Previous FQ' },
      { keyTt: '${PREVFY}', valueTt: 'Previous FY' },
      { keyTt: '${TOMORROWPLUS}', valueTt: 'Starting tomorrow' },
      { keyTt: '${THISYEAR}', valueTt: 'This Year' },
      { keyTt: '${YESTERDAYMINUS}', valueTt: 'Till Yesterday' },
      { keyTt: '${TODAY}', valueTt: 'Today' },
      { keyTt: '${TOMORROW}', valueTt: 'Tomorrow' },
    ],
    Picklist: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    Currency: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    TextArea: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    Email: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    URL: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    AutoNumber: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    IP: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'ends_with', valueTt: 'ends with' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'starts_with', valueTt: 'starts with' },
    ],
    LongInteger: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    Lookup: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    ServerAutoComplete: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    User: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    Tag: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    MultiLookup: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    Decimal: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    Percentage: [
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: 'greater_equal', valueTt: 'greater_equal' },
      { keyTt: 'greater_than', valueTt: 'greater_than' },
      { keyTt: 'less_equal', valueTt: 'less_equal' },
      { keyTt: 'less_than', valueTt: 'less_than' },
      { keyTt: 'not_between', valueTt: 'not between' },
      { keyTt: '!=', valueTt: 'not equal' },
    ],
    DateTime: [
      { keyTt: 'AgeinDays', valueTt: 'Age in Day' },
      { keyTt: 'between', valueTt: 'between' },
      { keyTt: '${THISFQ}', valueTt: 'Current FQ' },
      { keyTt: '${THISFY}', valueTt: 'Current FY' },
      { keyTt: '${THISMONTH}', valueTt: 'Current Month' },
      { keyTt: '${THISWEEK}', valueTt: 'Current Week' },
      { keyTt: 'DueinDays', valueTt: 'Due in Days' },
      { keyTt: '=', valueTt: 'equal' },
      { keyTt: '>', valueTt: 'greater_than' },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
      { keyTt: '${LASTMONTH}', valueTt: 'Last Month' },
      { keyTt: '${LASTWEEK}', valueTt: 'Last Week' },
      { keyTt: '${LASTYEAR}', valueTt: 'Last Year' },
      { keyTt: '<', valueTt: 'less_than' },
      { keyTt: '${NEXTFQ}', valueTt: 'Next FQ' },
      { keyTt: '${NEXTFY}', valueTt: 'Next FY' },
      { keyTt: '${NEXTMONTH}', valueTt: 'Next Month' },
      { keyTt: 'NEXTWEEK', valueTt: 'Next Week' },
      { keyTt: '${NEXTYEAR}', valueTt: 'Next Year' },
      { keyTt: '!=', valueTt: 'not equal' },
      { keyTt: 'not_between', valueTt: 'not_between' },
      { keyTt: '${PREVFQ}', valueTt: 'Previous FQ' },
      { keyTt: '${PREVFY}', valueTt: 'Previous FY' },
      { keyTt: '${TOMORROWPLUS}', valueTt: 'Starting tomorrow' },
      { keyTt: '${THISYEAR}', valueTt: 'This Year' },
      { keyTt: '${YESTERDAYMINUS}', valueTt: 'Till Yesterday' },
      { keyTt: '${TODAY}', valueTt: 'Today' },
      { keyTt: '${TOMORROW}', valueTt: 'Tomorrow' },
    ],
    Checkbox: [{ keyTt: '=', valueTt: 'equal' }],
    MultiPicklist: [
      { keyTt: 'contains', valueTt: 'contains' },
      { keyTt: "doesn't contain", valueTt: "doesn't contain" },
      { keyTt: 'is empty', valueTt: 'is empty' },
      { keyTt: 'is not empty', valueTt: 'is not empty' },
    ],
  };
  citeriaColumns: KeyValueModel[] = [
    { keyTt: 'siteOwner', valueTt: 'Site Owner', data: { type: 'Text' } },
    {
      keyTt: 'country',
      valueTt: 'Country',
      data: {
        type: 'Picklist',
        options: [
          { keyTt: 'Australia', valueTt: 'Australia' },
          { keyTt: 'AU', valueTt: 'Australia' },
        ],
      },
    },
    {
      keyTt: 'state',
      valueTt: 'State',
      data: {
        type: 'Picklist',
        options: [
          { keyTt: 'ACT', valueTt: 'Australian Capital Territory' },
          { keyTt: 'NT', valueTt: 'Northern Territory' },
          { keyTt: 'NSW', valueTt: 'New South Wales' },
          { keyTt: 'WA', valueTt: 'Western Australia' },
          { keyTt: 'SA', valueTt: 'South Australia' },
          { keyTt: 'QLD', valueTt: 'Queensland' },
          { keyTt: 'VIC', valueTt: 'Victoria' },
          { keyTt: 'TAS', valueTt: 'Tasmania' },
        ],
      },
      value:''
    },
    { keyTt: 'region', valueTt: 'Region', data: { type: 'Text' } },
    {
      keyTt: 'siteCode',
      valueTt: 'Site Code',
      data: {
        type: 'ServerAutoComplete',
        config: {
          idName: {
            id: 'siteCode',
            name: 'siteCode',
          },
          lookupApiConfig: {
            method: 'POST',
            rootUrl: 'dx-lcnc-rm-api',
            api: `${'dx-lcnc-rm-api'}/v1/module/record`,
            customSearchWithGenriceService: true,
            body: {
              module: 'Site',
              action: 'View',
              paginationRequest: {
                sortOrder: 'desc',
                sortBy: 'pkId',
                pageNo: 0,
                pageSize: 10,
              },
            },
          },
          tableSettings: {
            leftActions: [
              {
                icon: 'refresh',
                label: 'Refresh',
                type: 'refresh',
              },
            ],
            pageSize: 10,
            pagination: true,
            paginationFirstLastButtons: true,
            singleRowSelect: false,
            multiSelect: true,
          },
          lookUpHeaderSettings: {
            isServiceDefined: false,
          },
          additionalFilter: [
            {
              label: 'state',
              operator: 'eq',
              type: 'SELECT',
              field: 'state',
              options: [
                { keyTt: 'ACT', valueTt: 'Australian Capital Territory' },
                { keyTt: 'NT', valueTt: 'Northern Territory' },
                { keyTt: 'NSW', valueTt: 'New South Wales' },
                { keyTt: 'WA', valueTt: 'Western Australia' },
                { keyTt: 'SA', valueTt: 'South Australia' },
                { keyTt: 'QLD', valueTt: 'Queensland' },
                { keyTt: 'VIC', valueTt: 'Victoria' },
                { keyTt: 'TAS', valueTt: 'Tasmania' },
              ]
            }
          ]
        } as DxLookupModalConfig,
      },
    },
    { keyTt: 'siteName', valueTt: 'Site Name', data: { type: 'Text' } },
    { keyTt: 'siteId', valueTt: 'Site Number', data: { type: 'Text' } },
    {
      keyTt: 'siteType',
      valueTt: 'Site Type',
      data: {
        type: 'Picklist',
        options: [
          { keyTt: 'Small Cell', valueTt: 'Small Cell' },
          { keyTt: 'Macrocell', valueTt: 'Macrocell' },
          { keyTt: 'Indoor Small Cell', valueTt: 'Indoor Small Cell' },
          { keyTt: 'HUB', valueTt: 'HUB' },
          { keyTt: 'High Gain', valueTt: 'High Gain' },
          { keyTt: 'Minicell', valueTt: 'Minicell' },
          { keyTt: 'Sat Small Cell', valueTt: 'Sat Small Cell' },
          { keyTt: 'EXCHANGE', valueTt: 'EXCHANGE' },
          { keyTt: 'PICO Cell', valueTt: 'PICO Cell' },
          { keyTt: 'Medium Gain', valueTt: 'Medium Gain' },
          { keyTt: 'In Building', valueTt: 'In Building' },
          { keyTt: 'CUSTOMER', valueTt: 'CUSTOMER' },
          { keyTt: 'Low Gain', valueTt: 'Low Gain' },
          { keyTt: 'COW', valueTt: 'COW' },
          { keyTt: 'Mini Macro', valueTt: 'Mini Macro' },
        ],
      },
    },
    {
      keyTt: 'siteFunctions',
      valueTt: 'Site Functions',
      data: {
        type: 'MultiPicklist',
        options: [
          { keyTt: 'HUB', valueTt: 'HUB' },
          { keyTt: 'POI', valueTt: 'POI' },
          { keyTt: 'Customer Site Type 1', valueTt: 'Customer Site Type 1' },
          { keyTt: 'SAP', valueTt: 'SAP' },
          { keyTt: 'POP', valueTt: 'POP' },
          { keyTt: 'FAN', valueTt: 'FAN' },
          {
            keyTt: 'Commercial Data Center',
            valueTt: 'Commercial Data Center',
          },
          { keyTt: 'Customer Site Type 2', valueTt: 'Customer Site Type 2' },
          { keyTt: 'OPTUS Fibre Connected', valueTt: 'OPTUS Fibre Connected' },
          { keyTt: 'Mobile Joint Venture', valueTt: 'Mobile Joint Venture' },
          { keyTt: 'Exchange', valueTt: 'Exchange' },
          { keyTt: 'Earth Station', valueTt: 'Earth Station' },
          { keyTt: 'BTS', valueTt: 'BTS' },
          { keyTt: 'OPTUS Data Center', valueTt: 'OPTUS Data Center' },
          { keyTt: 'Customer Data Center', valueTt: 'Customer Data Center' },
          { keyTt: 'Copper Connected', valueTt: 'Copper Connected' },
          {
            keyTt: 'UECOMM Fibre Connected',
            valueTt: 'UECOMM Fibre Connected',
          },
          { keyTt: 'Overseas', valueTt: 'Overseas' },
          { keyTt: 'CEV', valueTt: 'CEV' },
          { keyTt: 'RAN', valueTt: 'RAN' },
          { keyTt: 'NBN POI', valueTt: 'NBN POI' },
        ],
      },
    },
    { keyTt: 'Tags', valueTt: 'Tags', data: { type: 'Tag' } },
    { keyTt: 'changedAt', valueTt: 'Changed At', data: { type: 'DateTime' } },
    { keyTt: 'createdAt', valueTt: 'Created At', data: { type: 'DateTime' } },
    { keyTt: 'createdBy', valueTt: 'Created By', data: { type: 'User' } },
    { keyTt: 'changedBy', valueTt: 'Changed By', data: { type: 'User' } },
  ];
}
